@startuml

skinparam groupInheritance 3

package ucf.assignments {

    package model {
        class Todo implements java.io.Serializable, java.lang.Comparable{
            - description : StringProperty
            - dueDate : ObjectProperty<LocalDate>
            - complete : BooleanProperty

            + Todo(): Todo
            + Todo(String description, LocalDate dueDate): Todo
            + Todo(String description, LocalDate dueDate, boolean complete): Todo

            + getDesc(): String
            + setDesc(String description): void
            + descriptionProperty(): StringProperty
            + getDueDate(): LocalDate
            + setDueDate(LocalDate dueDate): void
            + dueDateProperty(): ObjectProperty<LocalDate>
            + isComplete(): boolean
            + setComplete(boolean complete): void
            + completeProperty(): BooleanProperty

            + toString(): String
            + equals(Object obj): int
            + hashCode(): int
            + compareTo(Todo todo): int
        }

        class ToDoDAO {
            - listFile : File

            + ToDoDAO(): ToDoDAO

            + getListFile(): File
            + setListFileToNull(): void

            + create(File dir, String fileName): void
            + open(File file): void
            + read(): Collection<? extends ToDo>
            + save(Collection<? extends ToDo> toDoList): boolean
            + delete(): boolean
        }
    }

    package util {

        class ToDoListSerializer {
            - {static} LOCAL_DATE_PROPERTY_TYPE : Type
            - {static} COLLECTION_TYPE : Type
            - {static} GSON : Gson

            + {static} fromJson(File json) : Collection<? extends ToDo>
            + {static} toJson(Collection<? extends ToDo> list) : String
        }

        class StringPropertySerializer implements com.google.gson.JsonSerializer {
           + serialize(SimpleStringProperty src, Type typeOfSrc,
           JsonSerializationContext context):  JsonElement
        }

        class LocalDatePropertySerializer implements com.google.gson.JsonSerializer{
            + serialize(ObjectProperty<LocalDate> src, Type typeOfSrc,
            JsonSerializationContext context): JsonElement
        }

        class BooleanPropertySerializer implements com.google.gson.JsonSerializer {
            + serialize(SimpleBooleanProperty src, Type typeOfSrc,
            JsonSerializationContext context): JsonElement
        }

        class StringPropertyDeserializer implements com.google.gson.JsonDeserializer {
            + deserialize(JsonElement json, Type typeOfT,
            JsonDeserializationContext context): StringProperty
        }

        class LocalDatePropertyDeserializer implements com.google.gson.JsonDeserializer {
            + deserialize(JsonElement json, Type typeOfT,
            JsonDeserializationContext context): ObjectProperty<LocalDate>
        }

        class BooleanPropertyDeserializer implements com.google.gson.JsonDeserializer {
            + deserialize(JsonElement json, Type typeOfT,
            JsonDeserializationContext context): BooleanProperty
        }

        ToDoDAO .> ToDoListSerializer : «uses» >
        ToDoListSerializer +- StringPropertySerializer
        ToDoListSerializer +-- LocalDatePropertySerializer
        ToDoListSerializer +--- BooleanPropertySerializer
        ToDoListSerializer +--- StringPropertyDeserializer
        ToDoListSerializer +-- LocalDatePropertyDeserializer
        ToDoListSerializer +- BooleanPropertyDeserializer
    }



    class ToDoListManager {
        + start(Stage primaryStage): void
        + {static} main(String[] args): void
    }

}

package com.google.gson {

    interface JsonSerializer<T> {
        + serialize(T src, Type typeOfSrc,
        JsonSerializationContext context): JsonElement
    }

    interface JsonDeserializer<T> {
        + deserialize(JsonElement json, Type typeOfT,
        JsonDeserializationContext context): T
    }

    class Gson {

    }

    class GsonBuilder {

    }


}

ToDoListSerializer .> com.google.gson.GsonBuilder : «uses» >
ToDoListSerializer o-- com.google.gson.Gson

package java.lang {

    interface Comparable<Todo>{
        + compareTo(Todo o): int
    }
}



@enduml