@startuml

skinparam groupInheritance 3

package util {

    class ToDoListSerializer {
        - {static} LOCAL_DATE_PROPERTY_TYPE : Type
        - {static} COLLECTION_TYPE : Type
        - {static} GSON : Gson

        + {static} fromJson(File json) : Collection<? extends ToDo>
        + {static} toJson(Collection<? extends ToDo> list) : String
    }

    class StringPropertySerializer implements com.google.gson.JsonSerializer {
       + serialize(SimpleStringProperty src, Type typeOfSrc,
       JsonSerializationContext context):  JsonElement
    }

    class LocalDatePropertySerializer implements com.google.gson.JsonSerializer{
        + serialize(ObjectProperty<LocalDate> src, Type typeOfSrc,
        JsonSerializationContext context): JsonElement
    }

    class BooleanPropertySerializer implements com.google.gson.JsonSerializer {
        + serialize(SimpleBooleanProperty src, Type typeOfSrc,
        JsonSerializationContext context): JsonElement
    }

    class StringPropertyDeserializer implements com.google.gson.JsonDeserializer {
        + deserialize(JsonElement json, Type typeOfT,
        JsonDeserializationContext context): StringProperty
    }

    class LocalDatePropertyDeserializer implements com.google.gson.JsonDeserializer {
        + deserialize(JsonElement json, Type typeOfT,
        JsonDeserializationContext context): ObjectProperty<LocalDate>
    }

    class BooleanPropertyDeserializer implements com.google.gson.JsonDeserializer {
        + deserialize(JsonElement json, Type typeOfT,
        JsonDeserializationContext context): BooleanProperty
    }

    ToDoListSerializer +- StringPropertySerializer
    ToDoListSerializer +- LocalDatePropertySerializer
    ToDoListSerializer +- BooleanPropertySerializer
    ToDoListSerializer +-- StringPropertyDeserializer
    ToDoListSerializer +-- LocalDatePropertyDeserializer
    ToDoListSerializer +-- BooleanPropertyDeserializer
}

package com.google.gson {

    interface JsonSerializer<T> {
        + serialize(T src, Type typeOfSrc,
        JsonSerializationContext context): JsonElement
    }

    interface JsonDeserializer<T> {
        + deserialize(JsonElement json, Type typeOfT,
        JsonDeserializationContext context): T
    }
}

ToDoListSerializer o- com.google.gson.Gson


@enduml